name: deploy mailer

on: 
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: lp13.rpiambulance.com
        username: ${{ secrets.LP13_SSH_USERNAME }}
        password: ${{ secrets.LP13_SSH_PASSWORD }}
        script: ${{ secrets.LP13_SSH_SCRIPT }} mailer